### ISSUE TITLE
[ERROR] Failed to execute goal on project sigtest-generator

### ISSUE THREAD

**Issue by Gabrieledevx** [secure-software-engineering/upcy#13]
When I try :
Install UpCy-Base (libraries for building dependency graph and running call graph analysis)
Clone the UpCy-Base repository git clone https://github.com/anddann/upcy-base
change into the folder cd upcy-base
Build and install SootDiff in your local maven repository mvn clean compile install

I got the error below: 

`[ERROR] Failed to execute goal on project sigtest-generator: Could not resolve dependencies for project de.upb.upcy.base:sigtest-generator:jar:0.5.1-SNAPSHOT: Failed to collect dependencies at de.upb:sootdiff:jar:2.3-SNAPSHOT: Failed to read artifact descriptor for de.upb:sootdiff:jar:2.3-SNAPSHOT: The following artifacts could not be resolved: de.upb:sootdiff:pom:2.3-SNAPSHOT (absent): Could not transfer artifact de.upb:sootdiff:pom:2.3-SNAPSHOT from/to github (https://maven.pkg.github.com/secure-software-engineering/sootdiff): status code: 401, reason phrase: Unauthorized (401) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :sigtest-generator`

Any news about this error ? or I have a misspelled step ? 

Here's the version of programs that  I use now 

*java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

*mvn -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: C:\Program Files\apache-maven-3.9.6
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_202\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

*docker -v
Docker version 24.0.7, build afdd53b

**Comment by anddann** [comment]
Hi @Gabrieledevx ,
as the error message states, it could not find the dependency sootdiff:2.3
Please compile and install before sootdiff https://github.com/secure-software-engineering/sootdiff/

**Comment by Gabrieledevx** [comment]
Hi @anddann, sure, I tried your recommended steps and I got it. However, over the weekend, I was thinking about how the OS runtime and dependencies work. I tried it on Ubuntu OS and now (at the time of writing this) I have succeeded in solving it. Here's a screenshot:

![image](https://github.com/secure-software-engineering/upcy/assets/57644772/60f147cc-e4f1-4c6a-b3b5-96fc66831581)

Note:

The first step is to change permissions for the user executing Docker:

sudo usermod -aG docker $USER 

Where $USER is the current user executing:

sudo mvn clean compile install

I tried changing permissions on the folder /tmp because I was getting an error with Neo4j.

It seems like your Maven build is failing due to a test error. The critical part of the error message is related to Neo4j and the inability to obtain a lock on the store lock file in the /tmp directory. Here are the relevant parts of the error:

Caused by: org.neo4j.kernel.StoreLockException: Unable to obtain lock on store lock file: /tmp/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)

This error indicates that there is a lock file in the specified directory (/tmp) preventing Neo4j from starting. Here are a few steps you can take to resolve this issue:

Check if Neo4j is running: Ensure that no other instance of Neo4j is running on your machine, as it might have acquired a lock on the database directory.

Delete the lock file: Manually delete the /tmp/store_lock file if it exists. This can be done using the following command:

rm /tmp/store_lock

Check directory permissions: Make sure that the directory where Neo4j is trying to create the lock file (/tmp) is writable. You can check and change the permissions using the following commands:

ls -ld /tmp
chmod +w /tmp

Ensure that the user running the Maven build has the necessary permissions to write to the specified directory.

Run Maven build again: After performing the above steps, try running your Maven build again.
Thanks a lot.

Here's the version of the programs that I'm using now:

Thanks a lot 


Thanks a lot.

Here's the version of the programs that I'm using now:

gabriel@vivobook:~/secsoftwareeng/mvn-ecosystem-graph$ mvn -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /opt/apache-maven-3.9.6
Java version: 11.0.21, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.5.0-18-generic", arch: "amd64", family: "unix"
gabriel@vivobook:~/secsoftwareeng/mvn-ecosystem-graph$ docker -v
Docker version 25.0.3, build 4debf41

**Comment by anddann** [comment]
Hi @Gabrieledevx ,

I'm sorry but I do not get the problem nor your comment.
When you say "I was thinking about how the OS runtime and dependencies work".
Actually Maven Dependencies and the OS should not intfer with each other.
What was your docker problem? 
For compiling the Maven modules you only need a running version of docker on your machine installed.

For the compilation, Neo4j is not required.
I guess it is not even used for any of the tests.
